import { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip as RechartsTooltip,
  XAxis,
  YAxis,
} from "recharts";
import pptxgen from "pptxgenjs";
import { Download, Loader2 } from "lucide-react";
import { ChatWidget } from "../../components/chat/ChatWidget";
import { sendChatMessage } from "../../services/api/chat.api";

const fallbackPerformanceData = [
  { name: "Jan", revenue: 4000, target: 2400 },
  { name: "Feb", revenue: 3000, target: 1398 },
  { name: "Mar", revenue: 2000, target: 9800 },
];
const fallbackMetricData = [
  { name: "Q1", growth: 85, attrition: 15 },
  { name: "Q2", growth: 72, attrition: 18 },
];

type Kpi = { label: string; value: string; subtext: string };
type Insight = { title: string; description: string };
type Chart1 = { title: string; data: Record<string, unknown>[]; lineKey: string };
type Chart2 = {
  title: string;
  data: Record<string, unknown>[];
  barKey1: string;
  barKey2?: string;
};

type DynamicDashboard = {
  kpis?: Kpi[];
  chart1?: Chart1;
  chart2?: Chart2;
  insights?: Insight[];
  rateLimit?: boolean;
};

type LocationState = {
  sources?: string[];
  reportTitle?: string;
  fileData?: string;
  instructions?: string;
};

export function GeneralReportViewPage() {
  const location = useLocation();
  const navigate = useNavigate();
  const state = (location.state as LocationState | null) ?? null;
  const [isExporting, setIsExporting] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [dynamicData, setDynamicData] = useState<DynamicDashboard | null>(null);
  const [loadError, setLoadError] = useState<string | null>(null);

  const sources = state?.sources ?? ["uploaded_file.csv"];
  const dynamicTitle = state?.reportTitle || "General Performance Report";
  const fileData = state?.fileData || "";
  const instructions = state?.instructions || "";

  useEffect(() => {
    if (!fileData) {
      setIsLoading(false);
      return;
    }

    let cancelled = false;
    async function generateDynamicLayout() {
      try {
        const prompt = `You are a dashboard generator. Based on this CSV data snippet:\n\n${fileData}\n\n${
          instructions ? `User instructions: ${instructions}\n\n` : ""
        }Generate a JSON object strictly matching this schema. RETURN ONLY VALID JSON without markdown formatting. Do not include introductory text:
{
  "kpis": [
    { "label": "String (e.g. Total Responses)", "value": "String (e.g. 1,450)", "subtext": "String (e.g. +5% vs prev)" }
  ],
  "chart1": {
    "title": "String",
    "data": [ { "name": "Category", "val1": 10 } ],
    "lineKey": "val1"
  },
  "chart2": {
    "title": "String",
    "data": [ { "name": "Category", "val1": 20, "val2": 15 } ],
    "barKey1": "val1",
    "barKey2": "val2"
  },
  "insights": [
    { "title": "String", "description": "String (2-3 sentences explaining a pattern)" }
  ]
}

IMPORTANT: Output ONLY valid JSON matching the schema. Do NOT invent citations or evidence IDs.`;

        const data = await sendChatMessage({ message: prompt });
        if (cancelled) return;

        const jsonMatch = data.reply.match(/\{[\s\S]*\}/);
        if (!jsonMatch) throw new Error("No JSON object found in response");

        const parsed = JSON.parse(jsonMatch[0]) as DynamicDashboard;
        setDynamicData(parsed);
      } catch (err) {
        if (!cancelled) {
          console.error("Failed to parse dynamic JSON", err);
          setLoadError(err instanceof Error ? err.message : "Could not generate dashboard");
        }
      } finally {
        if (!cancelled) setIsLoading(false);
      }
    }

    void generateDynamicLayout();
    return () => {
      cancelled = true;
    };
  }, [fileData, instructions]);

  function exportToPPT() {
    setIsExporting(true);
    const pres = new pptxgen();

    const slide1 = pres.addSlide();
    slide1.background = { color: "F8FAFC" };
    slide1.addText(dynamicTitle, {
      x: 1,
      y: 1.5,
      w: "80%",
      h: 1,
      fontSize: 32,
      bold: true,
      color: "1E293B",
      align: "center",
    });
    slide1.addText("Generated by AI Presentation System", {
      x: 1,
      y: 2.5,
      w: "80%",
      h: 0.5,
      fontSize: 16,
      color: "64748B",
      align: "center",
    });

    const slide2 = pres.addSlide();
    slide2.addText("Executive Summary", {
      x: 0.5,
      y: 0.5,
      w: "90%",
      fontSize: 24,
      bold: true,
      color: "1E293B",
    });
    const insightBullets =
      dynamicData?.insights?.map((i) => ({
        text: `${i.title}: ${i.description}`,
        options: { bullet: true as const },
      })) ?? [
        { text: `Metrics for ${dynamicTitle} show solid performance.`, options: { bullet: true as const } },
        { text: "Detailed breakdowns align with expected variations.", options: { bullet: true as const } },
      ];
    slide2.addText(insightBullets, {
      x: 0.5,
      y: 1.2,
      w: "80%",
      h: 3,
      fontSize: 14,
      color: "334155",
    });

    void pres
      .writeFile({ fileName: `${dynamicTitle.replace(/\s+/g, "_")}.pptx` })
      .then(() => setIsExporting(false))
      .catch(() => setIsExporting(false));
  }

  const reportContext = JSON.stringify({
    reportType: dynamicTitle,
    sources,
    dataPreview: dynamicData || "No parsed data available",
  });

  if (isLoading) {
    return (
      <div className="max-w-6xl mx-auto p-8 flex flex-col items-center justify-center min-h-[60vh] gap-4">
        <Loader2 className="w-10 h-10 text-indigo-600 animate-spin" />
        <h2 className="text-xl font-bold text-gray-800 animate-pulse">
          Analyzing file structure & generating dynamic dashboard...
        </h2>
      </div>
    );
  }

  if (dynamicData?.rateLimit) {
    return (
      <div className="max-w-4xl mx-auto mt-20 p-8 flex flex-col items-center justify-center text-center bg-red-50 border-2 border-red-200 rounded-2xl">
        <h2 className="text-2xl font-bold text-red-700 mb-2">API Rate Limit Exceeded</h2>
        <p className="text-red-600 mb-6">Please wait a minute before trying again.</p>
        <button
          type="button"
          onClick={() => navigate("/")}
          className="bg-red-600 text-white px-6 py-2 rounded-lg font-semibold hover:bg-red-700 transition"
        >
          Go Back
        </button>
      </div>
    );
  }

  const kpis: Kpi[] = dynamicData?.kpis ?? [
    { label: "Data Rows", value: fileData ? "Loaded" : "None", subtext: loadError ?? "Processed" },
    { label: "Format", value: "CSV", subtext: "Standard tabular" },
    { label: "Status", value: dynamicData ? "Active" : "Fallback", subtext: "Live session" },
  ];

  const chart1: Chart1 = dynamicData?.chart1 ?? {
    title: "Primary Trend",
    data: fallbackPerformanceData,
    lineKey: "revenue",
  };

  const chart2: Chart2 = dynamicData?.chart2 ?? {
    title: "Category Distribution",
    data: fallbackMetricData,
    barKey1: "growth",
    barKey2: "attrition",
  };

  return (
    <div className="max-w-6xl mx-auto p-8 pb-20">
      <div className="bg-indigo-900 text-white rounded-xl p-6 mb-8 shadow-sm">
        <div className="flex justify-between items-start flex-wrap gap-3">
          <div>
            <h1 className="text-2xl font-bold mb-1">{dynamicTitle}</h1>
            <p className="text-sm text-indigo-200 mb-4">Based on data from: {sources.join(", ")}</p>
            {loadError && !dynamicData && (
              <p className="text-xs text-amber-200">
                LLM parse failed ({loadError}) — showing placeholder charts.
              </p>
            )}
            {!fileData && (
              <p className="text-xs text-indigo-200">
                No upload snippet — open from Home → General Report to generate from a file.
              </p>
            )}
          </div>
          <div className="flex gap-3">
            <button
              type="button"
              onClick={() => navigate("/")}
              className="flex items-center gap-2 bg-indigo-800 hover:bg-indigo-700 border border-indigo-600 px-4 py-2 rounded transition text-sm font-medium"
            >
              Back to Home
            </button>
            <button
              type="button"
              onClick={exportToPPT}
              disabled={isExporting}
              className="flex items-center gap-2 bg-white text-indigo-900 hover:bg-indigo-50 px-4 py-2 rounded font-semibold transition"
            >
              {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download size={18} />}
              Export to PPT
            </button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        {kpis.map((kpi, idx) => (
          <div
            key={idx}
            className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm flex flex-col justify-center"
          >
            <p className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-2">
              {kpi.label}
            </p>
            <h3 className="text-3xl font-black text-gray-800 mb-1">{kpi.value}</h3>
            <p className="text-sm font-medium text-green-600">{kpi.subtext}</p>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
        <div className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm">
          <h2 className="text-sm font-semibold text-gray-700 mb-6">{chart1.title}</h2>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={chart1.data}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5E7EB" />
                <XAxis
                  dataKey="name"
                  axisLine={false}
                  tickLine={false}
                  tick={{ fill: "#6B7280", fontSize: 12 }}
                  dy={10}
                />
                <YAxis
                  axisLine={false}
                  tickLine={false}
                  tick={{ fill: "#6B7280", fontSize: 12 }}
                />
                <RechartsTooltip
                  contentStyle={{
                    borderRadius: "8px",
                    border: "none",
                    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
                  }}
                />
                <Legend iconType="circle" wrapperStyle={{ paddingTop: "20px" }} />
                <Line
                  type="monotone"
                  dataKey={chart1.lineKey}
                  stroke="#4F46E5"
                  strokeWidth={3}
                  dot={{ r: 4, strokeWidth: 2 }}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm">
          <h2 className="text-sm font-semibold text-gray-700 mb-6">{chart2.title}</h2>
          <div className="h-64">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chart2.data} barSize={40}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E5E7EB" />
                <XAxis
                  dataKey="name"
                  axisLine={false}
                  tickLine={false}
                  tick={{ fill: "#6B7280", fontSize: 12 }}
                  dy={10}
                />
                <YAxis
                  axisLine={false}
                  tickLine={false}
                  tick={{ fill: "#6B7280", fontSize: 12 }}
                />
                <RechartsTooltip
                  cursor={{ fill: "#F3F4F6" }}
                  contentStyle={{
                    borderRadius: "8px",
                    border: "none",
                    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
                  }}
                />
                <Legend iconType="circle" wrapperStyle={{ paddingTop: "10px" }} />
                <Bar
                  name={chart2.barKey1}
                  dataKey={chart2.barKey1}
                  fill="#10B981"
                  radius={[4, 4, 0, 0]}
                />
                {chart2.barKey2 && (
                  <Bar
                    name={chart2.barKey2}
                    dataKey={chart2.barKey2}
                    fill="#F43F5E"
                    radius={[4, 4, 0, 0]}
                  />
                )}
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {dynamicData?.insights && dynamicData.insights.length > 0 && (
        <div className="bg-white p-8 rounded-xl border border-indigo-100 shadow-sm mb-8">
          <h2 className="text-lg font-bold text-gray-800 mb-4">Detected Patterns & Insights</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {dynamicData.insights.map((insight, idx) => (
              <div key={idx} className="bg-indigo-50/50 p-4 rounded-lg border border-indigo-100">
                <h3 className="font-semibold text-indigo-900 mb-1">{insight.title}</h3>
                <p className="text-sm text-indigo-700 leading-relaxed">{insight.description}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      <ChatWidget context={reportContext} title={`${dynamicTitle} Assistant`} />
    </div>
  );
}
